/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;
import Persistencia.IngredientesData;
import Modelo.Ingredientes;

/**
 *
 * @author Miguel
 */
public class AgregarIngredientes extends javax.swing.JInternalFrame {

DefaultTableModel modeloTabla = new DefaultTableModel(new String[]{"Ingrediente", "Calorías", "Condición"}, 0);
    private int filaEnEdicion;

    /**
     * Creates new form AgregarIngredientes
     */
    public AgregarIngredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTIngredientes = new javax.swing.JTable();
        jBModificar = new javax.swing.JButton();
        jBAlta = new javax.swing.JButton();
        jBbaja = new javax.swing.JButton();
        nombreTextField = new javax.swing.JTextField();
        caloriasTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBguardar = new javax.swing.JButton();

        jTIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Calorias", "Condicion"
            }
        ));
        jScrollPane1.setViewportView(jTIngredientes);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBAlta.setText("Alta");
        jBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAltaActionPerformed(evt);
            }
        });

        jBbaja.setText("Baja");
        jBbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diabetes", "Hipertension", "Celiaquismo" }));

        jLabel1.setText("Nombre");

        jLabel2.setText("Calorias");

        jLabel3.setText("Condicion");

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBModificar)
                        .addGap(50, 50, 50)
                        .addComponent(jBguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAlta)
                        .addGap(62, 62, 62)
                        .addComponent(jBbaja))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreTextField)
                            .addComponent(caloriasTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caloriasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(jBAlta)
                    .addComponent(jBbaja)
                    .addComponent(jBguardar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaActionPerformed

    String nombre = nombreTextField.getText();
    String caloriasStr = caloriasTextField.getText();
    String condicion = (String) jComboBox1.getSelectedItem();
        if (nombre.isEmpty() || caloriasStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese todos los datos.");
}
        try {
        int calorias = Integer.parseInt(caloriasStr);
        modeloTabla.addRow(new Object[]{nombre, calorias, condicion});
         nombreTextField.setText("");
        caloriasTextField.setText("");
        jComboBox1.setSelectedIndex(0);
        }
        catch (NumberFormatException e) {
         javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor numérico válido para las calorías.");
        }
    }//GEN-LAST:event_jBAltaActionPerformed

    private void jBbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTIngredientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar el ingrediente seleccionado?", 
            "Confirmación de baja", 
            javax.swing.JOptionPane.YES_NO_OPTION);
             if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // Eliminar la fila del modelo de la tabla
            DefaultTableModel modeloTabla = (DefaultTableModel) jTIngredientes.getModel();
            modeloTabla.removeRow(filaSeleccionada);
        }
             
        } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un ingrediente para eliminar.");
    }
    }//GEN-LAST:event_jBbajaActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
            int filaSeleccionada = jTIngredientes.getSelectedRow();
             if (filaSeleccionada != -1) {
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) jTIngredientes.getModel();
        nombreTextField.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
        caloriasTextField.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
        jComboBox1.setSelectedItem(modeloTabla.getValueAt(filaSeleccionada, 2).toString());
        this.filaEnEdicion = filaSeleccionada;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un ingrediente para modificar.");
    }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
    if (filaEnEdicion != -1) {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTIngredientes.getModel();
        modeloTabla.setValueAt(nombreTextField.getText(), filaEnEdicion, 0);
        modeloTabla.setValueAt(Integer.parseInt(caloriasTextField.getText()), filaEnEdicion, 1);
        modeloTabla.setValueAt(jComboBox1.getSelectedItem(), filaEnEdicion, 2);
        nombreTextField.setText("");
        caloriasTextField.setText("");
        jComboBox1.setSelectedIndex(0);
          filaEnEdicion = -1;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna fila en edición.");
    }
    }//GEN-LAST:event_jBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caloriasTextField;
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBbaja;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTIngredientes;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables
}
